# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  (1..3).each do |i|
   
    config.vm.define "node#{i}" do |node|
      node.vm.box = "elastic/centos-7-x86_64"
      node.vm.hostname="node#{i}"
      node.vm.network "public_network",bridge:"eth0" , ip:"192.168.1.18#{i}"
    
      node.vm.provision "shell", inline:<<-SHELL

        cd ~
        wget https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/zip/elasticsearch/2.3.5/elasticsearch-2.3.5.zip
        unzip elasticsearch-2.3.5.zip
        groupadd deepbay
        useradd -g deepbay -G root deepbay
        chown -R deepbay.deepbay elasticsearch-2.3.5
        su deepbay
	sed -i '23s/.*/node\.name: node#{i}/g' elasticsearch-2.3.5/config/elasticsearch.yml
        sed -i '17s/.*/cluster.name: my-application/g' elasticsearch-2.3.5/config/elasticsearch.yml
	sed -i '54s/.*/network.host: 192.168.1.18#{i}/g' elasticsearch-2.3.5/config/elasticsearch.yml
	sed -i '58s/.*/http\.port: 9200/g' elasticsearch-2.3.5/config/elasticsearch.yml
	sed -i '68s/.*/discovery.zen.ping.unicast.hosts: ["node1", "node2","node3"]/g' elasticsearch-2.3.5/config/elasticsearch.yml
	echo "192.168.1.181 node1">>/etc/hosts
	echo "192.168.1.182 node2">>/etc/hosts
	echo "192.168.1.183 node3">>/etc/hosts
	./elasticsearch-2.3.5/bin/elasticsearch>elasticsearch-2.3.5/logs/start.log 2>&1 &
        systemctl stop firewalld.service
      SHELL
    
    end


  end
end
