# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  (1..3).each do |i|
   
    config.vm.define "node#{i}" do |node|
      node.vm.box = "elastic/centos-7-x86_64"
      node.vm.hostname="node#{i}"
      node.vm.network "public_network",bridge:"eth0" , ip:"192.168.1.18#{i}"
    
      node.vm.provider :virtualbox do |v|
        v.memory = 8192
        v.cpus = 4
      end

      node.vm.provision "shell", inline:<<-SHELL

        sed -i "59a deepbay          soft    nofile          65536" /etc/security/limits.conf
	sed -i "59a deepbay          hard    nofile          65536" /etc/security/limits.conf
 	echo "vm.max_map_count=655360" >> /etc/sysctl.conf
	sysctl -p
	cd ~
        wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.6.zip
        unzip elasticsearch-5.6.6.zip
        groupadd deepbay
        useradd -g deepbay -G root deepbay
        chown -R deepbay.deepbay elasticsearch-5.6.6
        su deepbay

#	sed -i '22s/.*/ -Xms4g/g' elasticsearch-5.6.6/config/jvm.options
#	sed -i '23s/.*/ -Xmx4g/g' elasticsearch-5.6.6/config/jvm.options

        sed -i '17s/.*/cluster.name: my-application/g' elasticsearch-5.6.6/config/elasticsearch.yml
	sed -i '55s/.*/network.host: 192.168.1.18#{i}/g' elasticsearch-5.6.6/config/elasticsearch.yml
	sed -i '59s/.*/http\.port: 9200/g' elasticsearch-5.6.6/config/elasticsearch.yml
	sed -i '68s/.*/discovery.zen.ping.unicast.hosts: ["node1", "node2","node3"]/g' elasticsearch-5.6.6/config/elasticsearch.yml
	echo "192.168.1.181 node1">>/etc/hosts
	echo "192.168.1.182 node2">>/etc/hosts
	echo "192.168.1.183 node3">>/etc/hosts
	./elasticsearch-5.6.6/bin/elasticsearch>elasticsearch-5.6.6/logs/start.log 2>&1 &
        systemctl stop firewalld.service
      SHELL
    
    end


  end
end
